// funfact-api.js
const express = require('express');
const app = express();
const port = process.env.PORT || 3000;

const facts = [
  "Honey never spoils. Archaeologists have found 3000-year-old honey in ancient Egyptian tombs that’s still edible!",
  "The unicorn is the national animal of Scotland.",
  "A snail can sleep for 3 years.",
  "Octopuses have 3 hearts and blue blood.",
  "You can't hum while holding your nose.",
  "Bananas are berries, but strawberries aren’t.",
  "Sharks are older than trees.",
  "Wombat poop is cube-shaped.",
  "The Eiffel Tower can be 15 cm taller during hot days.",
  "Humans share 60% of their DNA with bananas.",
  "Sloths can hold their breath longer than dolphins can.",
  "The shortest war in history lasted 38 minutes.",
  "Butterflies taste with their feet.",
  "A group of flamingos is called a 'flamboyance'.",
  "There are more stars in the universe than grains of sand on Earth.",
  "Koalas sleep up to 22 hours a day.",
  "Dolphins have names for each other.",
  "The heart of a shrimp is located in its head.",
  "Cows have best friends and get stressed when separated.",
  "The longest wedding veil was the same length as 63.5 football fields.",
  "Sea otters hold hands while sleeping to keep from drifting apart.",
  "A jiffy is an actual unit of time (1/100th of a second).",
  "The oldest known joke is from 1900 BC.",
  "The inventor of the Pringles can is now buried in one.",
  "There are more fake flamingos in the world than real ones.",
  "Tigers have striped skin, not just striped fur.",
  "A bolt of lightning contains enough energy to toast 100,000 slices of bread.",
  "There are more trees on Earth than stars in the Milky Way.",
  "Sharks can live up to 500 years.",
  "The first computer bug was a real bug (a moth).",
  "Bananas are curved because they grow towards the sun.",
  "The world's largest snowflake was 15 inches wide.",
  "Sloths can rotate their heads nearly 270 degrees.",
  "Goats have rectangular pupils.",
  "A bolt of lightning is five times hotter than the surface of the sun.",
  "You produce about 25,000 quarts of saliva in a lifetime.",
  "Dolphins sleep with one eye open.",
  "The average cloud weighs about a million pounds.",
  "Sharks can detect a drop of blood in an Olympic-sized pool.",
  "Cows can walk upstairs but not downstairs.",
  "Humans glow faintly in the dark, but it's invisible to the naked eye.",
  "A day on Venus is longer than its year.",
  "Penguins propose with pebbles.",
  "Starfish can regrow their arms.",
  "Your brain uses 20% of your body's oxygen.",
  "Cats have fewer toes on their back paws.",
  "The shortest commercial flight lasts just 57 seconds.",
  "Octopuses can change color and texture instantly.",
  "The moon has moonquakes.",
  "The longest hiccuping spree lasted 68 years.",
  "The smallest bone in your body is in your ear.",
  "Crows are as smart as a 7-year-old child.",
  "Elephants can't jump.",
  "Butterflies can see ultraviolet light.",
  "The word 'nerd' was first coined by Dr. Seuss.",
  "Sharks don't have bones.",
  "You can’t sneeze with your eyes open.",
  "The world's oldest piece of chewing gum is 9,000 years old.",
  "Rats laugh when tickled.",
  "The inventor of the frisbee was turned into a frisbee after he died.",
  "Frogs absorb water through their skin.",
  "The Great Wall of China is not visible from space with the naked eye.",
  "A group of porcupines is called a 'prickle'.",
  "Polar bear skin is black underneath their white fur.",
  "The tallest tree is over 379 feet tall.",
  "Sea cucumbers fight by shooting out their own internal organs.",
  "A cat has 32 muscles in each ear.",
  "Koalas have fingerprints almost identical to humans.",
  "The first alarm clock could only ring at 4 a.m.",
  "Sharks have been around longer than dinosaurs.",
  "Slugs have four noses.",
  "There are more bacteria in your mouth than people on Earth.",
  "Some turtles can breathe through their butts.",
  "A cockroach can live several weeks without its head.",
  "Humans share 98.8% of their DNA with chimpanzees.",
  "The world’s smallest reptile is smaller than a paperclip.",
  "Lightning strikes about 8 million times per day worldwide.",
  "Cats can make over 100 vocal sounds.",
  "Jellyfish have been around for over 500 million years.",
  "Some bamboo species can grow up to 3 feet in 24 hours.",
  "The hummingbird is the only bird that can fly backwards.",
  "The human nose can remember 50,000 different scents.",
  "Octopuses have blue blood.",
  "Honeybees communicate through dance.",
  "The average person walks the equivalent of five times around the world in their lifetime.",
  "Sloths only poop once a week.",
  "The heart of a blue whale is the size of a small car.",
  "Some cats are allergic to humans.",
  "Sharks can go into a trance.",
  "The longest time between two twins being born is 87 days.",
  "Bats always turn left when exiting a cave.",
  "There are more stars in the sky than grains of sand on all Earth’s beaches.",
  "Humans and giraffes have the same number of neck bones.",
  "An ostrich's eye is bigger than its brain.",
  "Butterflies can taste with their feet.",
  "The human body contains enough fat to make seven bars of soap.",
  "The strongest muscle in the body is the tongue.",
  "A crocodile cannot stick its tongue out.",
  "A group of frogs is called an army."
];

app.get('/funfact', (req, res) => {
  const randomFact = facts[Math.floor(Math.random() * facts.length)];
  res.json({ fact: randomFact });
});

app.listen(port, () => {
  console.log(`Fun Fact API listening at http://localhost:${port}`);
});
