const express = require('express');
const app = express();

const funFacts = [
  "Honey never spoils. Archaeologists have found pots of honey in ancient Egyptian tombs that are over 3,000 years old and still perfectly good to eat.",
  "Octopuses have three hearts and blue blood.",
  "Bananas are berries, but strawberries aren't.",
  "A group of flamingos is called a 'flamboyance'.",
  "There's enough DNA in the human body to stretch from the sun to Pluto and back — 17 times.",
  "The Eiffel Tower can grow more than 6 inches during the summer due to the expansion of metal.",
  "Wombat poop is cube-shaped.",
  "A day on Venus is longer than a year on Venus.",
  "Sharks existed before trees.",
  "Sloths can hold their breath longer than dolphins can.",
  "There's a basketball court on the top floor of the U.S. Supreme Court building. It's nicknamed 'The Highest Court in the Land'.",
  "An octopus has nine brains — one central brain and one mini-brain in each arm.",
  "There are more fake flamingos in the world than real ones.",
  "A cloud can weigh more than a million pounds.",
  "You can't hum while holding your nose closed.",
  "A bolt of lightning is five times hotter than the surface of the sun.",
  "Cats can’t taste sweetness.",
  "The unicorn is the national animal of Scotland.",
  "The majority of your brain is fat — about 60%.",
  "The word 'nerd' was first coined by Dr. Seuss.",
  "Some turtles can breathe through their butts.",
  "You blink about 20 times a minute — that's over 10 million times a year.",
  "Butterflies can taste with their feet.",
  "Cows have best friends and get stressed when separated.",
  "Humans share about 60% of their DNA with bananas.",
  "You can hear a blue whale's heartbeat from 2 miles away.",
  "There's a species of jellyfish that can live forever.",
  "Pineapples take two years to grow.",
  "Water makes different pouring sounds depending on the temperature.",
  "The total weight of all the ants on Earth equals the total weight of all humans.",
  "A crocodile cannot stick its tongue out.",
  "Some sea cucumbers fight by shooting out their own organs.",
  "The dot over the letter “i” is called a tittle.",
  "Mosquitoes are attracted to people who just ate bananas.",
  "A single strand of spaghetti is called a spaghetto.",
  "Snails can sleep for up to three years.",
  "There's a McDonald's on every continent except Antarctica.",
  "Banging your head against a wall for one hour burns 150 calories.",
  "Elephants are the only animals that can't jump.",
  "The inventor of the Pringles can is buried in one.",
  "The longest hiccuping spree lasted 68 years.",
  "Starfish don’t have brains.",
  "Peanuts aren’t technically nuts — they’re legumes.",
  "Some cats are allergic to humans.",
  "A small child could swim through the veins of a blue whale.",
  "Avocados are berries, but blackberries aren’t.",
  "A sneeze travels about 100 miles per hour.",
  "The word “strengths” is the longest word with only one vowel.",
  "Tigers have striped skin, not just striped fur.",
  "Otters hold hands while sleeping to keep from drifting apart.",
  "A shrimp's heart is located in its head.",
  "The smell of freshly-cut grass is a plant distress call.",
  "The longest wedding veil was longer than 63 football fields.",
  "Your stomach gets a new lining every 3 to 4 days to prevent it from digesting itself.",
  "Froot Loops are all the same flavor despite their different colors.",
  "The Twitter bird actually has a name — it's Larry.",
  "A blue whale's tongue weighs as much as an elephant.",
  "Hot water freezes faster than cold water — it's called the Mpemba effect.",
  "There's a species of spider named after Johnny Cash.",
  "A jiffy is an actual unit of time: 1/100th of a second.",
  "Koalas have fingerprints that are almost identical to humans'.",
  "Octopuses taste with their arms.",
  "The average person walks the equivalent of five times around the world in their lifetime.",
  "There's a town in Norway called Hell, and it freezes over every winter.",
  "Goosebumps are meant to ward off predators by making us look bigger.",
  "You can’t breathe and swallow at the same time.",
  "There's a basketball team named after a literary character: The Cleveland Cavaliers — based on the adventurous 'cavalier'.",
  "Alaska is the westernmost, easternmost, and northernmost state in the U.S.",
  "Turtles can breathe through their butts.",
  "The Empire State Building has its own zip code.",
  "The average cumulus cloud weighs about 1.1 million pounds.",
  "Wearing headphones for just an hour could increase the bacteria in your ear by 700 times.",
  "A group of crows is called a murder.",
  "Banging your head burns calories, but it’s not recommended.",
  "Your nose can remember 50,000 different scents.",
  "The first oranges weren’t orange — they were green.",
  "Rats laugh when tickled.",
  "Apples float because they’re 25% air.",
  "Pigs can't look up into the sky.",
  "There are more stars in the universe than grains of sand on all Earth’s beaches.",
  "The tongue is the only muscle in one’s body that is attached from one end.",
  "Your heartbeat syncs with the music you listen to.",
  "An ostrich's eye is bigger than its brain.",
  "More people are allergic to cow’s milk than any other food.",
  "The inventor of the microwave only received $2 for his discovery.",
  "Octopuses have rectangular pupils.",
  "Bubble wrap was originally invented as wallpaper.",
  "Human thigh bones are stronger than concrete.",
  "A bolt of lightning contains enough energy to toast 100,000 slices of bread.",
  "In 2006, a Coca-Cola employee offered to sell Coca-Cola secrets to Pepsi. Pepsi responded by notifying Coca-Cola.",
  "Birds don't urinate.",
  "The word 'why' is the only word in English that starts with 'wh' but ends in 'y'.",
  "The longest English word without a vowel is 'rhythms'.",
  "The shortest war in history was between Britain and Zanzibar on August 27, 1896. Zanzibar surrendered after 38 minutes."
];

app.get('/', (req, res) => {
  const randomIndex = Math.floor(Math.random() * funFacts.length);
  const fact = funFacts[randomIndex];
  res.json({
    data: {
      fact: fact
    }
  });
});

const PORT = process.env.PORT || 3000;
app.listen(PORT, () => {
  console.log(`Fun fact service is running on port ${PORT}`);
});
